"""Generate the profile README's SVG blocks. Run: python3 tools/make_readme_art.py

Reads the logos in assets/ and writes assets/header.svg and assets/featured.svg.
Colours and type follow brendondgr.com: black ground, #00FFCC accent, mono chips.
GitHub renders README images with no network and no stylesheet, so every colour
is a literal here and every font is asked for by system stack.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets"

# --- palette -----------------------------------------------------------------
PANEL_BG, PANEL_EDGE = "#050505", "#17201d"
CHIP_BG, CHIP_EDGE = "#0c100f", "#1f2a27"
TEXT, CHIP_TEXT, MUTED = "#ffffff", "#c4cbc8", "#7d8784"
ACCENT = "#00ffcc"
DISC = "#f6f2e8"

SANS = "ui-sans-serif,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif"
MONO = "ui-monospace,SFMono-Regular,Menlo,Consolas,'DejaVu Sans Mono',monospace"

W = 1000
CHIP_H, CHIP_FS, CHIP_GAP, CHIP_PAD = 30, 13.0, 9.0, 14.0
DOT_R, DOT_GUTTER, ADVANCE = 4.0, 13.0, 0.6


def inner(path: Path) -> str:
    """The drawing inside a logo file, with the wrapper, metadata and CSS gone.

    GitHub will not render one SVG referenced from another, so the paths have to
    be copied in on every run. Illustrator's class-based fills are inlined,
    because a <style> block is not guaranteed to survive GitHub's sanitiser.
    """
    raw = path.read_text()
    classes = dict(re.findall(r"\.([\w-]+)\s*\{\s*fill:\s*([^;}\s]+)", raw))
    raw = re.sub(r"<metadata>.*?</metadata>", "", raw, flags=re.S)
    raw = re.sub(r"<defs.*?(?:/>|</defs>)", "", raw, flags=re.S)
    body = raw[raw.index(">", raw.index("<svg")) + 1 : raw.rindex("</svg>")]
    for name, fill in classes.items():
        body = body.replace(f'class="{name}"', f'fill="{fill}"')
    return body.strip()


def viewbox(path: Path) -> tuple[float, float]:
    nums = re.search(r'viewBox="([\d.\s-]+)"', path.read_text()).group(1).split()
    return float(nums[2]), float(nums[3])


def place(path: Path, cx: float, cy: float, box: float, fill: str | None = None) -> str:
    """Scale a logo to fit a box of `box` points and centre it on (cx, cy)."""
    return fit(path, cx, cy, box, box, fill)


def fit(path: Path, cx: float, cy: float, bw: float, bh: float, fill=None) -> str:
    """Contain a logo in a bw x bh box centred on (cx, cy), aspect kept.

    `fill` paints marks that carry no fill of their own; the PULSE mono mark is
    black by default and would vanish into the panel.
    """
    w, h = viewbox(path)
    s = min(bw / w, bh / h)
    paint = f' fill="{fill}"' if fill else ""
    return (
        f'<g{paint} transform="translate({cx - w * s / 2:.1f},{cy - h * s / 2:.1f}) '
        f'scale({s:.6f})">\n    {inner(path)}\n  </g>'
    )


def esc(s: str) -> str:
    """XML-escape a label, leaving any entity already written by hand alone."""
    return re.sub(r"&(?![#a-zA-Z][\w#]*;)", "&amp;", s).replace("<", "&lt;")


def chip_width(label: str, dot: str | None) -> float:
    return CHIP_PAD * 2 + len(label) * CHIP_FS * ADVANCE + (DOT_GUTTER if dot else 0.0)


def chips(items, y, x=None):
    """A row of pill chips. Centred on the panel unless `x` gives a left edge.

    Text cannot be measured before rendering, so the labels are monospace and
    laid out at the ~0.6 em advance every monospace face shares.
    """
    widths = [chip_width(*i) for i in items]
    if x is None:
        x = (W - (sum(widths) + CHIP_GAP * (len(items) - 1))) / 2
    parts = []
    for (label, dot), width in zip(items, widths):
        text_x = x + CHIP_PAD
        parts.append(
            f'<rect x="{x:.1f}" y="{y:g}" width="{width:.1f}" height="{CHIP_H}" '
            f'rx="{CHIP_H / 2:g}" fill="{CHIP_BG}" stroke="{CHIP_EDGE}" />'
        )
        if dot:
            parts.append(
                f'<circle cx="{text_x + DOT_R:.1f}" cy="{y + CHIP_H / 2:.1f}" '
                f'r="{DOT_R:g}" fill="{dot}" />'
            )
            text_x += DOT_GUTTER
        parts.append(
            f'<text x="{text_x:.1f}" y="{y + CHIP_H / 2 + 4.6:.1f}" font-family="{MONO}" '
            f'font-size="{CHIP_FS:g}" fill="{CHIP_TEXT}">{esc(label)}</text>'
        )
        x += width + CHIP_GAP
    return "\n  ".join(parts)


def panel(h: float, body: str, label: str, accent_bar: bool = False) -> str:
    bar = (
        f'<rect x="0.5" y="24" width="3" height="{h - 48:g}" rx="1.5" fill="{ACCENT}" />'
        if accent_bar
        else ""
    )
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {h:g}" width="{W}" '
        f'height="{h:g}" role="img" aria-label="{label}">\n'
        f"  <!-- Generated by tools/make_readme_art.py - edit that, not this. -->\n"
        f'  <rect x="0.5" y="0.5" width="{W - 1}" height="{h - 1:g}" rx="22" '
        f'fill="{PANEL_BG}" stroke="{PANEL_EDGE}" />\n'
        f"  {bar}\n  {body}\n</svg>\n"
    )


def text(x, y, s, size, fill=TEXT, font=SANS, anchor="start", weight="400", ls=None):
    extra = f' letter-spacing="{ls}"' if ls is not None else ""
    return (
        f'<text x="{x:g}" y="{y:g}" text-anchor="{anchor}" font-family="{font}" '
        f'font-size="{size:g}" font-weight="{weight}" fill="{fill}"{extra}>{esc(s)}</text>'
    )


# --- block 1: the header -----------------------------------------------------
HEADER_ALT = (
    "Brendon DGR, applied AI researcher - a PhD student at Florida State University's "
    "PULSE Lab working on agentic AI, scientific discovery, cybersecurity, AI for health "
    "and applied LLMs."
)
FOCUS = [
    ("Agentic AI", ACCENT),
    ("Scientific Discovery", "#4fa3ff"),
    ("Cybersecurity", "#c792ea"),
    ("AI for Health", "#ff6b81"),
    ("Applied LLMs", "#ffcb6b"),
]


def header():
    cx = W / 2
    h = 386
    body = "\n  ".join(
        [
            f'<circle cx="{cx:g}" cy="118" r="66" fill="#0a0f0e" stroke="{PANEL_EDGE}" />',
            place(ASSETS / "logo-bdgr.svg", cx, 118, 78),
            text(cx, 232, "BRENDON DGR", 62, TEXT, SANS, "middle", "700", "-1.5"),
            text(cx, 266, "Applied AI Researcher", 21, MUTED, SANS, "middle"),
            text(
                cx, 300,
                "AGENTIC SYSTEMS &#183; SCIENTIFIC DISCOVERY &#183; SOFTWARE",
                12, ACCENT, MONO, "middle", "500", "3.4",
            ),
            chips(FOCUS, 330),
        ]
    )
    (ASSETS / "header.svg").write_text(panel(h, body, HEADER_ALT))


# --- block 2: the nav buttons ------------------------------------------------
# One file per button, because a link wraps a whole image: three destinations
# means three images.
BTN_H, BTN_FS, BTN_PAD, BTN_LS = 56, 15.0, 30.0, 1.6
BUTTONS = [
    ("btn-website", "WEBSITE", "brendondgr.com", True),
    ("btn-about", "ABOUT ME", "brendondgr.com/about", False),
    ("btn-projects", "PROJECTS", "brendondgr.com/projects", False),
]


def button(name, label, dest, primary):
    w = BTN_PAD * 2 + (len(label) * BTN_FS * ADVANCE) + BTN_LS * (len(label) - 1)
    fill, edge, fg = (
        (ACCENT, ACCENT, "#00110d") if primary else (CHIP_BG, "#243330", ACCENT)
    )
    out = (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w:.0f} {BTN_H}" '
        f'width="{w:.0f}" height="{BTN_H}" role="img" aria-label="{label.title()} - {dest}">\n'
        f"  <!-- Generated by tools/make_readme_art.py - edit that, not this. -->\n"
        f'  <rect x="1" y="1" width="{w - 2:.0f}" height="{BTN_H - 2}" rx="{BTN_H / 2 - 1:g}" '
        f'fill="{fill}" stroke="{edge}" stroke-width="1.5" />\n'
        f'  {text(w / 2 + BTN_LS / 2, BTN_H / 2 + 5.4, label, BTN_FS, fg, MONO, "middle", "600", BTN_LS)}\n'
        f"</svg>\n"
    )
    (ASSETS / f"{name}.svg").write_text(out)


# --- block 3: the sites ------------------------------------------------------
# One file per card, for the same reason as the buttons: each one is a link.
CARD_H, PLATE_W, PLATE_H = 104, 150, 72
SITES = [
    {
        "name": "site-brendondgr",
        "logo": "logo-bdgr.svg",
        "paint": None,
        "domain": "brendondgr.com",
        "blurb": "My own site: the writing, the project pages and the CV, designed and built from scratch.",
        "tag": "DESIGN &#183; BUILD &#183; HOSTING",
    },
    {
        "name": "site-pulse",
        "logo": "logo-pulse.svg",
        "paint": DISC,
        "domain": "pulse.sc.fsu.edu",
        "blurb": "The PULSE Lab at FSU: people, publications and research, with a branding system to match.",
        "tag": "DESIGN &#183; BUILD",
    },
    {
        "name": "site-scai",
        "logo": "logo-scai.svg",
        "paint": None,
        "domain": "sc-ai.net",
        "blurb": "The Scientific Computing AI Seminar: the weekly schedule, the speakers and the archive.",
        "tag": "DESIGN &#183; BUILD",
    },
]


def site(spec):
    plate_cx, cy = 22 + PLATE_W / 2, CARD_H / 2
    left = 22 + PLATE_W + 30
    body = "\n  ".join(
        [
            f'<rect x="22" y="{cy - PLATE_H / 2:g}" width="{PLATE_W}" height="{PLATE_H}" '
            f'rx="14" fill="#0a0f0e" stroke="{PANEL_EDGE}" />',
            fit(ASSETS / spec["logo"], plate_cx, cy, PLATE_W - 34, PLATE_H - 24, spec["paint"]),
            text(left, 47, spec["domain"], 17, TEXT, MONO, "start", "600"),
            text(left, 71, spec["blurb"], 14, MUTED),
            text(W - 30, 57, spec["tag"], 10.5, ACCENT, MONO, "end", "500", "2.6"),
        ]
    )
    label = f'{spec["domain"]} - {spec["blurb"]}'
    (ASSETS / f'{spec["name"]}.svg').write_text(panel(CARD_H, body, label))


# --- block 4: the featured project ------------------------------------------
FEATURED = {
    "logo": "logo-mytheca.svg",
    "kicker": "FEATURED PROJECT",
    "title": "Mytheca",
    "lines": (
        "AI roleplay in worlds you write yourself. Every character runs as its own agent,",
        "and the engine checks each move &#8212; dialogue, action, stat change &#8212; before it reaches the page.",
    ),
    "tags": [("Agentic AI", ACCENT), ("Creative Tools", "#c792ea"), ("Search & Retrieval", "#4fa3ff")],
    "stack": [(n, None) for n in ("FastAPI", "Next.js", "Neo4j", "Qdrant", "hybrid search")],
    "footer": "brendondgr.com/projects/mytheca",
    "alt": (
        "Featured project, Mytheca: AI roleplay in worlds you write yourself, where every "
        "character runs as its own agent and the engine checks each move before it reaches "
        "the page. Built with FastAPI, Next.js, Neo4j, Qdrant and hybrid search."
    ),
}


def featured():
    h, pad, mark = 268, 40, 96
    left = pad + mark + 34
    p = FEATURED
    body = "\n  ".join(
        [
            f'<circle cx="{pad + mark / 2:g}" cy="{h / 2:g}" r="{mark * 0.66:.1f}" '
            f'fill="#0a0f0e" stroke="{PANEL_EDGE}" />',
            place(ASSETS / p["logo"], pad + mark / 2, h / 2, mark * 0.80),
            text(left, 60, p["kicker"], 12, ACCENT, MONO, "start", "500", "3.4"),
            text(left, 104, p["title"], 40, TEXT, SANS, "start", "700", "-0.8"),
            text(left, 138, p["lines"][0], 16, MUTED),
            text(left, 162, p["lines"][1], 16, MUTED),
            chips(p["tags"], 184, left),
            chips(p["stack"], 222, left),
            text(W - pad, 60, p["footer"], 12.5, MUTED, MONO, "end"),
        ]
    )
    (ASSETS / "featured.svg").write_text(panel(h, body, p["alt"], accent_bar=True))


# The featured card is built and ready; it is switched off until there is a
# project on the page whose source is public.
FEATURED_ENABLED = False

header()
for spec in BUTTONS:
    button(*spec)
for spec in SITES:
    site(spec)
if FEATURED_ENABLED:
    featured()
print("wrote assets/header.svg, the nav buttons and the site cards")
